language: objective-c

install:
  - brew update
  - brew install chruby
  - git clone git://github.com/terlar/fish-tank.git
  - cd fish-tank
  - sudo make install
  - cd ..

before_script:
  - echo yes | rvm implode
  - __rvm_unload
  - sudo mkdir -p /usr/gnu/bin

script:
  - make test
