sudo: false

os:
  # FIXME:
  # - linux
  - osx

env:
  - FISH_VERSION="--HEAD"
  - FISH_VERSION="" # 2.2.0

language: c

install:
  - brew install fish $FISH_VERSION
  - brew install chruby
  - mkdir -p fishtape
  - curl -L https://github.com/fisherman/fishtape/archive/1.3.1.tar.gz | tar --strip-components=1 -xzC fishtape
  - cd fishtape
  - make install
  - cd ..
  - fish --version

before_script:
  - rm -rf $HOME/.rvm $HOME/.rvmrc
  - __rvm_unload
  - echo "source $HOME/.config/fish/functions/fishtape.fish" >> $HOME/.config/fish/config.fish
  - ls -lah $HOME/.config/fish/
  - cat $HOME/.config/fish/config.fish
  - fish -c "fishtape --help"
  - make test/opt/rubies
  - ls -lah /Users/travis/build/JeanMertz/chruby-fish/test/opt/rubies/

script: make test
